services:
  node:
    container_name: backdash-node
    image: node:lts-alpine3.17
    working_dir: /app
    depends_on:
      - mongo
    user: "root"
    volumes:
      - ./:/app
    env_file:
      - .env
    ports:
      - "8081:8081"
    command: "npm run dev"

  mongo:
    image: mongo:latest
    container_name: backdash-mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin